import Container from '@/components/Layout/Container'
import Head from 'next/head'

export default function Articles() {
  return (
    <>
      <Head>
        <title>Articles - Industrial Engineers Club</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Container>
        <h1>Articles page</h1>
      </Container>
    </>
  )
}
